### ISSUE TITLE
It was possible to refer to files on disk before

### ISSUE THREAD

**Issue by kberov** [jhthorsen/json-validator#1]
When the functionality was in Swagger2::SchemaValidator I was able to refer from one schema file to places in other files. Now the whole reference is considered as file name and not as it was before (filename.ext#/path/subpath).
Example:
Having the file /home/berov/opt/private_dev/api/lib/API/etc/APIs/users.yaml I was refering in it to a "definitions" file and an exact place in it: "lib/API/etc/APIs/definitions.yaml#/definitions/Users".
users.yaml
```yaml
      responses:
        200:
          description: A paged array of users
          schema: {$ref: "lib/API/etc/APIs/definitions.yaml#/definitions/Users"}
```
definitions.yaml:
```yaml
---
definitions:
  User:
    required:
      - id
      - group_id
      - login_name
    properties:
      id:
        type: integer
      group_id:
        type: integer
      login_name:
        type: string
  Users:
    type: array
    items:
      $ref: User
```
Now I see the following error (JSON_VALIDATOR_DEBUG=1):

```bash
Server available at http://[::]:5000
This module is replaced by JSON::Validator. at /home/berov/opt/public_dev/swagger2/lib/Swagger2/SchemaValidator.pm line 17, <DATA> line 2231.
[JSON::Validator] Loading schema from /home/berov/opt/private_dev/api/lib/API/etc/APIs/users.yaml (/home/berov/opt/private_dev/api/lib/API/etc/APIs/users.yaml)
[JSON::Validator] Register /home/berov/opt/private_dev/api/lib/API/etc/APIs/users.yaml
[JSON::Validator] Register /home/berov/opt/private_dev/api/lib/API/etc/APIs/users.yaml
[JSON::Validator] Resolve lib/API/etc/APIs/definitions.yaml#/definitions/Error
[JSON::Validator] Loading schema from lib/API/etc/APIs/definitions.yaml#/definitions/Error (lib/API/etc/APIs/definitions.yaml)
Use of uninitialized value $doc in concatenation (.) or string at /home/berov/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/JSON/Validator.pm line 347, <DATA> line 2231.
Can't load application from file "/home/berov/opt/private_dev/api/bin/api": Could not load document from lib/API/etc/APIs/definitions.yaml#/definitions/Error: Can't open file "lib/API/etc/APIs/definitions.yaml#/definitions/Error": No such file or directory at /home/berov/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/JSON/Validator.pm line 341.
 () at /home/berov/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/JSON/Validator.pm line 347, <DATA> line 2231.
Compilation failed in require at (eval 48) line 1, <DATA> line 2231.

```
